project:
  type: book
  output-dir: docs

book:
  title: "Global Fishing Watch documentation"
  date: last-modified
  # announcement:
  #   content: "**Alert** - this is some information that you should pay attention to"
  repo-url: https://github.com/GlobalFishingWatch/GFW_technical_documentation
  repo-actions: [issue]
  
  favicon: figures/GFW_logo.png ##proportions are not quite right

  sidebar:
    title: "Documentation Materials"
    style: "floating"
    search: true
    pinned: true
    tools:
      - icon: house-door-fill
        href: https://globalfishingwatch.org/
    # - icon: twitter
    #   href: [link to bluesky?]

  chapters:
    - index.md # intorduction
    
    - part: "Data Reference"
      chapters: 
        - files/data-updates.md
        - files/bigquery-datasets.md
        - files/bigquery-pipe3-table-reference.md
        - files/bigquery-pipe2.5-table-reference.md
        - files/bigquery-key-concepts.md
        - files/bigquery-in-products.md
      
    - part: "Vessel Identity"
      chapters: 
        - files/vessel-identity.md
        - files/identity-tables.md
        - files/vessel-database.md
        - files/vessel-info-tables.md
        - files/product-vessel-info-summary-pvis.md
        
    - part: "GFW Data?"
      chapters: 
      - files/fishing-effort-and-vessel-presence.md
      - files/fishing-events.md
      - files/encounters.md
      - files/loitering.md
      - files/gaps.md
      - files/anchorages-voyages-port-visits.md 
      - files/vms-data-sources.md
      - files/country-codes.md
      - files/coverage.md
      - files/pipeline.md
        
    - part: "Imagery"
      chapters: 
      - files/sar-object-detections.md
      - files/satellite-timing-offset-table.md
      - files/s2-vessel-detections.md
      - files/viirs.md
      
  
    - part: "Reference Layers"
      chapters:
      - files/areas-spatial-region-sources.md
      # - files/spatial-region-sources-and-methodology.md
      - files/areas-eez-boundaries.md
      - files/areas-12-nm-boundary.md
      - files/areas-rfmos.md
      - files/areas-fao-areas.md
      - files/areas-high-seas-pockets.md
      - files/areas-high-seas.md
      - files/areas-protected-seas.md
      - files/areas-wdpa-marine-mpas.md
      - files/areas-point-in-polygon-test-using-regions.md
      - files/areas-updating-layers-in-pipe_regions.md
  
  
    - part: "Resources"
      chapters:
      - files/wiki-documentation-standards.md
      - files/helpful-resources.md
      - files/data-products-page-template.md
      # - files/gfw-data-training-materials.md


# bibliography: references.bib

format:
  html:
    theme: cosmo
