project:
  type: book
  output-dir: docs

book:
  title: "Global Fishing Watch documentation"
  date: last-modified
  # announcement:
  #   content: "**Alert** - this is some information that you should pay attention to"
  repo-url: https://github.com/GlobalFishingWatch/GFW_technical_documentation
  repo-actions: [issue]
  
  favicon: figures/GFW_logo.png ##proportions are not quite right

  sidebar:
    title: "Documentation Materials"
    style: "floating"
    search: true
    pinned: true
    tools:
      - icon: house-door-fill
        href: https://globalfishingwatch.org/
    # - icon: twitter
    #   href: [link to bluesky?]

  chapters:
    - index.md # intorduction
    
    - part: "Data Reference"
      chapters: 
        - data-updates.md #(PART) Data Updates
        - bigquery-datasets.md #(PART) Big Query
        - bigquery-pipe3-table-reference.md
        - bigquery-pipe2.5-table-reference.md
        - key-concepts.md #(BigQuery Key Concepts)
        - bigquery-in-products.md
      
     - part: "Vessel Identity"
      chapters: 
        - vessel-identity.md
        - identity-tables.md
        - vessel-database.md
        - vessel-info-tables.md
        - product-vessel-info-summary-pvis.md
    - fishing-effort-and-vessel-presence.md
    
    - fishing-events.md #(PART) Events
    - encounters.md
    - loitering.md
    - gaps.md
    - anchorages-and-voyages.md # Anchorages, voyages and port visits
    - sar-object-detections.md
    - vms.md #VMS Data Sources
    - spatial-regions-sources-and-methodology.md
    - areas-eez-boundaries.md
    - areas-12-nm-boundary.md
    - areas-rfmos.md
    - areas-fao-areas.md
    - areas-high-seas-pockets.md
    - areas-high-seas.md
    - areas-protected-seas.md
    - areas-wdpa-marine-mpas.md
    - areas-how-to-point-in-polygon-in-bigquery.md
    - areas-how-to-update-layer-in-pipe-regions.md
    - country-codes.md
    - coverage.md
    - satellite-timing-offset-table.md
    - pipeline.md
    - wiki-documentation-standards.md #Wiki Page Requirements
    - helpful-resources.md #Internal materials
    - data-products-page-template.md
    - training-materials-README.md #(PART) Training materials


# bibliography: references.bib

format:
  html:
    theme: cosmo
